"""empty message

Revision ID: 20192976b87e
Revises: 
Create Date: 2020-06-02 10:06:51.215999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20192976b87e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
