"""empty message

Revision ID: 59c9ad07bccf
Revises: 20192976b87e
Create Date: 2020-06-02 10:11:43.731826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c9ad07bccf'
down_revision = '20192976b87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'price')
    # ### end Alembic commands ###
