"""empty message

Revision ID: 5af53dab57ad
Revises: d0ea78f82594
Create Date: 2020-06-02 16:15:33.598226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af53dab57ad'
down_revision = 'd0ea78f82594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'filename')
    # ### end Alembic commands ###
