"""empty message

Revision ID: 72465f986c14
Revises: 5af53dab57ad
Create Date: 2020-06-02 19:32:28.590353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72465f986c14'
down_revision = '5af53dab57ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('profile_pic', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'student_id')
    op.drop_table('student')
    # ### end Alembic commands ###
