"""empty message

Revision ID: b89b672bcc5a
Revises: 7472645c93ec
Create Date: 2020-06-03 07:40:37.528629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89b672bcc5a'
down_revision = '7472645c93ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subs',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['audiobook.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['listener.id'], )
    )
    op.drop_table('audio_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('speaker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audio_book_pkey')
    )
    op.drop_table('subs')
    op.drop_table('audiobook')
    # ### end Alembic commands ###
