"""empty message

Revision ID: c9fb29509843
Revises: 59c9ad07bccf
Create Date: 2020-06-02 13:13:12.840593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fb29509843'
down_revision = '59c9ad07bccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cover_page', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'cover_page')
    # ### end Alembic commands ###
