"""empty message

Revision ID: d0ea78f82594
Revises: c9fb29509843
Create Date: 2020-06-02 13:33:13.778239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0ea78f82594'
down_revision = 'c9fb29509843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'cover_page')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cover_page', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
